"""
OKX交易所API配置模板
请将以下信息替换为您的实际API信息，然后重命名为config.py
"""

# OKX交易所API配置
OKX_API_KEY = "your_api_key_here"
OKX_SECRET_KEY = "your_secret_key_here"
OKX_PASSPHRASE = "your_passphrase_here"

# 交易参数配置
SYMBOLS = ["BTC-USDT-SWAP", "ETH-USDT-SWAP", "SOL-USDT-SWAP", "BNB-USDT-SWAP", "AVAX-USDT-SWAP"]

# 策略参数
MACD_FAST = 6
MACD_SLOW = 16
MACD_SIGNAL = 9
ADX_PERIOD = 14
ADX_THRESHOLD = 25

# 风险控制
MAX_LEVERAGE_BTC = 125
MAX_LEVERAGE_ETH = 125
MAX_LEVERAGE_MAJOR = 100
MAX_LEVERAGE_OTHERS = 75
LEVERAGE_MIN = 3
DEFAULT_LEVERAGE = 20

# 震荡策略参数
BOLLINGER_PERIOD = 20
BOLLINGER_STD = 2
RSI_PERIOD = 14
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
STOCHASTIC_K = 14
STOCHASTIC_D = 3
ATR_PERIOD = 14