# Railway 项目配置
# 使用 Nixpacks 自动识别 Python 并安装 requirements.txt
[build]
builder = "nixpacks"

# 部署与服务配置
[[services]]
name = "okx-three-indicators-bot"
start = "python -u main.py"
restartPolicy = "always"

# 运行时环境变量（可被 Railway Dashboard Variables 覆盖）
[services.env]
POS_MODE = "hedge"
TIMEFRAME = "30m"
SCAN_INTERVAL = "180"
DRY_RUN = "false"
LOG_LEVEL = "INFO"
SUPERTREND_PERIOD = "10"
SUPERTREND_MULTIPLIER = "2.8"
QQE_RSI_PERIOD = "14"
QQE_SF = "5"
AV2_PERIOD = "10"
AV2_ATR_MULTIPLIER = "2.2"
DEFAULT_LEVERAGE = "5"
BUDGET_USDT = "5"
USE_BALANCE_AS_MARGIN = "true"
MARGIN_UTILIZATION = "1.0"